### ISSUE TITLE
Project Approval Request -  Alptium eLearning

### ISSUE THREAD

**Issue by Majape** [alptium/marija.peric#3]

**Comment by valentinajemuovic** [comment]
@Majape, please check, the "Projects" part on the right side panel is not filled in, you need to click on it, select tab Organization and then click on "Java Project"... this is needed so that it appears on my dashboard....

**Comment by valentinajemuovic** [comment]
I now fixed it.

**Comment by valentinajemuovic** [comment]
@Majape, I have created the repository and granted you access here https://github.com/alptium/elearning
